server:
  port: "8080"
  read_timeout: 15s
  write_timeout: 15s

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  cache_ttl: 1h

llm:
  endpoint: "https://api.openai.com/v1/chat/completions"
  api_key: ""  
  model: "gpt-3.5-turbo"
  max_tokens: 500
  timeout: 30s

slm:
  api_key: ""  
  model_name: "microsoft/Phi-3-mini-4k-instruct" 
  max_concurrent: 10
  max_tokens: 200
  timeout: 30s

router:
  complexity_threshold: 0.65
  latency_budget_ms: 500
  cost_threshold_usd: 0.001
