server:
  port: "8080"
  read_timeout: 15s
  write_timeout: 15s

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  cache_ttl: 1h

semantic_cache:
  enabled: true
  similarity_threshold: 0.85
  api_key: ""

llm:
  endpoint: "https://api.openai.com/v1/chat/completions"
  api_key: ""  
  model: "gpt-3.5-turbo"
  max_tokens: 500
  timeout: 30s

slm:
  strategy: hybrid
  aggregation_fn: weighted
  chain_threshold: 0.7
  max_concurrent: 10
  max_tokens: 200
  timeout: 30s
  models:
    - name: llama-3.1-8b-instant
      endpoint: https://api.groq.com/openai/v1
      api_key: ""
      weight: 1.5
    - name: llama-3.3-70b-versatile
      endpoint: https://api.groq.com/openai/v1
      api_key: ""
      weight: 2.0
    - name: mixtral-8x7b-32768
      endpoint: https://api.groq.com/openai/v1
      api_key: ""
      weight: 1.8

router:
  complexity_threshold: 0.65
  latency_budget_ms: 500
  cost_threshold_usd: 0.001
